name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: "Publish packages"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run tests for @bluvo/sdk-ts
        run: pnpm -F @bluvo/sdk-ts test

      - name: Run tests for @bluvo/react
        run: pnpm -F @bluvo/react test

      - name: Build packages
        run: |
          pnpm -F @bluvo/sdk-ts build
          pnpm -F @bluvo/react build

      - name: Configure .npmrc for authentication
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @bluvo/sdk-ts
        run: |
          pnpm -F @bluvo/sdk-ts publish --no-git-checks --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @bluvo/react
        run: |
          pnpm -F @bluvo/react publish --no-git-checks --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}